name: gltf
version: 2.0.0-dev.3.11
description: Library for loading and validating glTF 2.0 assets
homepage: https://github.com/KhronosGroup/glTF-Validator

dependencies:
  args: '^2.4.2'
  isolate: '^2.1.1'
  meta: '^1.16.0'
  path: '^1.8.3'
  vector_math: '^2.1.4'
  yaml: '^3.1.2'

dev_dependencies:
  archive: '^3.4.10'
  build_runner: '^2.3.3'
  build_version: '^2.1.1'
  build_web_compilers: '^3.2.7'
  grinder: '^0.9.4'
  js: '^0.6.7'
  node_preamble: '^2.0.2'
  test: '^1.24.3'

environment:
  sdk: '>=2.11.99 <3.0.0'

executables:
  gltf_validator: